# Generated by Django 4.2 on 2023-10-31 19:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
        ('feeling', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feeling',
            name='like_or_dislike',
            field=models.IntegerField(choices=[(-1, 'none'), (0, 'dislike'), (1, 'like')], default=-1),
        ),
        migrations.AlterField(
            model_name='feeling',
            name='profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='feelings', to='profiles.profile'),
        ),
    ]
